window.MULTIPIXELS_STORE = {
  currency: "EUR",
  quoteResponse: "24 à 48h",
  shipping: "Livraison partout en France ou retrait atelier à Rang-du-Fliers",
  stripe: {
    mode: "pending",
    enabled: false
  },
  products: [
    {
      id: "bc03t-noir",
      slug: "t-shirt-premium-noir",
      name: "T-shirt premium BC03T",
      category: "tshirts",
      segmentGroups: ["homme", "femme", "enfant"],
      audience: "Particuliers, clubs, pros",
      price: 16,
      minimum: "À partir de 5 pièces",
      image: "assets/catalogue/tshirt/BC03T/BC03T noir.jpg",
      imageAlt: "T-shirt premium noir MULTIPIXELS",
      shortDescription: "Base polyvalente pour flocage ou DTF, idéale pour séries événementielles et tenues d'équipe.",
      description: "Un t-shirt équilibré entre tenue, confort et budget, recommandé pour collections, associations et opérations de communication.",
      techniques: ["Flocage", "DTF", "Broderie légère"],
      colors: ["Noir", "Blanc", "Navy", "Ash"],
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      featured: true,
      localSeo: "Berck, Rang-du-Fliers, Abbeville, Amiens, Le Touquet"
    },
    {
      id: "bc03t-blanc",
      slug: "t-shirt-premium-blanc",
      name: "T-shirt premium BC03T blanc",
      category: "tshirts",
      audience: "Associations, événements, communication",
      price: 16,
      minimum: "À partir de 5 pièces",
      image: "assets/catalogue/tshirt/BC03T/BC03T blanc.jpg",
      imageAlt: "T-shirt premium blanc MULTIPIXELS",
      shortDescription: "Support lumineux et lisible pour visuels francs, logos colorés et séries promotionnelles.",
      description: "Une base simple et polyvalente pour les demandes à fort impact visuel, idéale pour événementiel et communication.",
      techniques: ["Flocage", "DTF"],
      colors: ["Blanc"],
      sizes: ["XS", "S", "M", "L", "XL", "XXL"]
    },
    {
      id: "polo-signature",
      slug: "polo-signature",
      name: "Polo signature entreprise",
      category: "polos",
      segmentGroups: ["homme", "femme", "workwear"],
      audience: "Entreprises, artisans, restauration",
      price: 25,
      minimum: "À partir de 5 pièces",
      image: "assets/Galerie/3.jpeg",
      imageAlt: "Polo brodé Multipixels",
      shortDescription: "Le support corporate par excellence pour un rendu brodé net et durable.",
      description: "Pensé pour les équipes terrain, les artisans et les marques qui veulent une image soignée.",
      techniques: ["Broderie", "DTF discret"],
      colors: ["Navy", "Noir", "Blanc"],
      sizes: ["S", "M", "L", "XL", "XXL"]
    },
    {
      id: "hoodie-premium",
      slug: "hoodie-premium",
      name: "Hoodie premium atelier",
      category: "sweats",
      audience: "Clubs, marques, écoles, streetwear",
      price: 39,
      minimum: "À partir de 5 pièces",
      image: "assets/Galerie/4.jpeg",
      imageAlt: "Sweat personnalisé Multipixels",
      shortDescription: "Pièce forte pour collections, dotations et cadeaux clients.",
      description: "Un sweat à forte valeur perçue, conçu pour accueillir un marquage poitrine, dos ou manche.",
      techniques: ["DTF", "Flocage", "Broderie"],
      colors: ["Noir", "Navy", "Gris"],
      sizes: ["S", "M", "L", "XL", "XXL"]
    },
    {
      id: "softshell-pro",
      slug: "softshell-pro",
      name: "Softshell pro performance",
      category: "workwear",
      segmentGroups: ["homme", "femme", "workwear"],
      audience: "BTP, services, logistique, maintenance",
      price: 59,
      minimum: "À partir de 5 pièces",
      image: "assets/Galerie/6.jpeg",
      imageAlt: "Vêtement de travail personnalisé Multipixels",
      shortDescription: "Une référence sérieuse pour les équipes qui ont besoin d'un vêtement technique et valorisant.",
      description: "Softshell robuste pour les équipes pro qui veulent conjuguer image, confort et durabilité.",
      techniques: ["Broderie", "DTF"],
      colors: ["Noir", "Anthracite", "Navy"],
      sizes: ["S", "M", "L", "XL", "XXL", "3XL"]
    },
    {
      id: "serviette-brodee",
      slug: "serviette-brodee",
      name: "Serviette brodée premium",
      category: "accessoires",
      audience: "Hôtellerie, cadeaux, coffrets premium",
      price: 20,
      minimum: "À partir de 3 pièces",
      image: "assets/Galerie/9.jpeg",
      imageAlt: "Serviette brodée premium Multipixels",
      shortDescription: "Support premium pour cadeaux, spa, chambres d'hôtes et coffrets personnalisés.",
      description: "Une finition élégante et durable pour les projets où la matière et la tenue dans le temps sont prioritaires.",
      techniques: ["Broderie"],
      colors: ["Blanc", "Noir", "Beige"],
      sizes: ["Unique"]
    }
  ]
};
